### ISSUE TITLE
Edge browser detects wrong version

### ISSUE THREAD

**Issue by tb-mtg** [OrbintSoft/yauaa.netstandard#1]
I tried your [demo](https://try.yauaa.basjes.nl/) site with Edge browser and it returned user agent

`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/18.17763`

but incorrectly says version is 18, but it actually is 44.17763.1.0 as show below from the app settings:

![image](https://user-images.githubusercontent.com/12589600/49563903-e8fa2e80-f975-11e8-8c85-280a3c083f68.png)

Can you fix so that is show the correct version?

**Comment by OrbintSoft** [comment]
Sorry, this is a porting of Java library https://github.com/nielsbasjes/yauaa
The demo that you tried is Java version, because demo of this .NET project is not yet available, but we use the same yaml definitions, so you should report the issue there.
If you need, you can load your custom yaml defnitions.
Report here only if you find issues related to .NET version only.
Thank you anyway.

**Comment by OrbintSoft** [comment]
@tb-mtg Please use this feature on demo website to report the issue: ![agent-issue](https://user-images.githubusercontent.com/6378748/49564728-d9062e80-f924-11e8-9475-d3c5b79e2cf7.PNG)

**Comment by tb-mtg** [comment]
Ok, sorry about that. I have now raised the issue below:

https://github.com/nielsbasjes/yauaa/issues/130

**Comment by OrbintSoft** [comment]
I reopen so I notify you when I implement in .NET.
Now .NET version is still in active development, so I need some time before I can target last Java version.

**Comment by d0apga** [comment]
is there any update ?

**Comment by OrbintSoft** [comment]
Sorry for long delay, I am going to release version 5.8 that should address the issue.

**Comment by OrbintSoft** [comment]
Bug fixed with version 5.8-beta.3, you can try the Demo here: https://orbintsoft.azurewebsites.net/Yauaa/Demo
Soon I release the stable version.
