### ISSUE TITLE
YamlDotNet dependency

### ISSUE THREAD

**Issue by tb-mtg** [OrbintSoft/yauaa.netstandard#2]
You have a dependency on [YamlDotNet.Signed](https://www.nuget.org/packages/YamlDotNet.Signed/) which states:

> [Obsolete! This is a transition package to help migrating to YamlDotNet] A .NET library for YAML. YamlDotNet provides low level parsing and emitting of YAML as well as a high level object model similar to XmlDocument.

What not use [YamlDotNet](https://www.nuget.org/packages/YamlDotNet/) instead?

**Comment by OrbintSoft** [comment]
Because it was not signed, the library is the same. I'll investigate  further to know if I can migrate safely.

Ottieni Outlook per Android<https://aka.ms/ghei36>

________________________________

**Comment by OrbintSoft** [comment]
Sorry lately I was busy with my job.
It seems now they have signed YamlDotNet  and made obsolete the other version.
So  I upgraded the dependency in 5.6-rc.1
