### ISSUE TITLE
Problem filepath when using on linux platform 

### ISSUE THREAD

**Issue by Shawlee76** [OrbintSoft/yauaa.netstandard#3]
Hi,
I have this error when deploying my application on a linux platform :

OrbintSoft.Yauaa.Analyze.InvalidParserConfigurationException: Error reading resources: Could not find a part of the path '/var/www/html/webtvapi/YamlResources\UserAgents'. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path '/var/www/html/webtvapi/YamlResources\UserAgents'.

It seems be a problem with the antislash character when it tries to find the YamlResources folder.
How can I solve this problem ?

Thanks by advance.
Charlie

**Comment by OrbintSoft** [comment]
Thank you, I will check it as soon as possible.

Ottieni Outlook per Android<https://aka.ms/ghei36>

________________________________

**Comment by OrbintSoft** [comment]
@Shawlee76 sorry for late reply, Can you try the 5.9-rc.1 version?

**Comment by OrbintSoft** [comment]
Since I did not received any answer I considered it closed with 5.9.1

**Comment by Shawlee76** [comment]
Hi, sorry for late reply. I tested the new version and it works fine.
Thank you.

Regards,
Charlie

**Comment by OrbintSoft** [comment]
It's ok thank you. With version 5.14 I am planning to enable continuous integration on linux. because by now I am unable to test linux and check if everything works.

Ottieni Outlook per Android<https://aka.ms/ghei36>

________________________________

**Comment by Shawlee76** [comment]
Ok, fine.
